Initial commit, not working
Followed directions to create a package here;
http://angular-meteor.com/tutorials/angular1/3rd-party-libraries.
Errors thrown with module declaration.

Uncaught Error: [$injector:modulerr] Failed to instantiate module todos
due to:
Error: [$injector:modulerr] Failed to instantiate module angular-filter
due to:
Error: [$injector:nomod] Module 'angular-filter' is not available! You
either misspelled the module name or forgot to load it. If registering
a module ensure that you specify the dependencies as the second
argument.
http://errors.angularjs.org/1.4.6/$injector/nomod?p0=angular-filter
    at REGEX_STRING_REGEXP
(http://localhost:3000/packages/angular_angular.js?feeaf4750c9fd3ceafa9f
712f99a21ee6fef9b41:99:12)
    at
http://localhost:3000/packages/angular_angular.js?feeaf4750c9fd3ceafa9f7
12f99a21ee6fef9b41:2017:17
    at ensure
(http://localhost:3000/packages/angular_angular.js?feeaf4750c9fd3ceafa9f
712f99a21ee6fef9b41:1941:38)
    at module
(http://localhost:3000/packages/angular_angular.js?feeaf4750c9fd3ceafa9f
712f99a21ee6fef9b41:2015:14)
    at
http://localhost:3000/packages/angular_angular.js?feeaf4750c9fd3ceafa9f7
12f99a21ee6fef9b41:4419:22
    at forEach
(http://localhost:3000/packages/angular_angular.js?feeaf4750c9fd3ceafa9f
712f99a21ee6fef9b41:367:20)
    at loadModules
(http://localhost:3000/packages/angular_angular.js?feeaf4750c9fd3ceafa9f
712f99a21ee6fef9b41:4403:5)
    at
http://localhost:3000/packages/angular_angular.js?feeaf4750c9fd3ceafa9f7
12f99a21ee6fef9b41:4420:40
    at forEach
(http://localhost:3000/packages/angular_angular.js?feeaf4750c9fd3ceafa9f
712f99a21ee6fef9b41:367:20)
    at loadModules
(http://localhost:3000/packages/angular_angular.js?feeaf4750c9fd3ceafa9f
712f99a21ee6fef9b41:4403:5)
http://errors.angularjs.org/1.4.6/$injector/modulerr?p0=angular-filter&p
1=E…2Fangular_angular.js%3Ffeeaf4750c9fd3ceafa9f712f99a21ee6fef9b41%3A44
03%3A5)
    at REGEX_STRING_REGEXP
(http://localhost:3000/packages/angular_angular.js?feeaf4750c9fd3ceafa9f
712f99a21ee6fef9b41:99:12)
    at
http://localhost:3000/packages/angular_angular.js?feeaf4750c9fd3ceafa9f7
12f99a21ee6fef9b41:4442:15
    at forEach
(http://localhost:3000/packages/angular_angular.js?feeaf4750c9fd3ceafa9f
712f99a21ee6fef9b41:367:20)
    at loadModules
(http://localhost:3000/packages/angular_angular.js?feeaf4750c9fd3ceafa9f
712f99a21ee6fef9b41:4403:5)
    at
http://localhost:3000/packages/angular_angular.js?feeaf4750c9fd3ceafa9f7
12f99a21ee6fef9b41:4420:40
    at forEach
(http://localhost:3000/packages/angular_angular.js?feeaf4750c9fd3ceafa9f
712f99a21ee6fef9b41:367:20)
    at loadModules
(http://localhost:3000/packages/angular_angular.js?feeaf4750c9fd3ceafa9f
712f99a21ee6fef9b41:4403:5)
    at createInjector
(http://localhost:3000/packages/angular_angular.js?feeaf4750c9fd3ceafa9f
712f99a21ee6fef9b41:4328:11)
    at doBootstrap
(http://localhost:3000/packages/angular_angular.js?feeaf4750c9fd3ceafa9f
712f99a21ee6fef9b41:1688:20)
    at bootstrap
(http://localhost:3000/packages/angular_angular.js?feeaf4750c9fd3ceafa9f
712f99a21ee6fef9b41:1709:12)
http://errors.angularjs.org/1.4.6/$injector/modulerr?p0=todos&p1=Error%3
A%2…Fangular_angular.js%3Ffeeaf4750c9fd3ceafa9f712f99a21ee6fef9b41%3A170
9%3A12)REGEX_STRING_REGEXP @ angular_angular.js:76(anonymous function)
@ angular_angular.js:4419forEach @ angular_angular.js:344loadModules @
angular_angular.js:4380createInjector @
angular_angular.js:4305doBootstrap @ angular_angular.js:1665bootstrap @
angular_angular.js:1686angularInit @ angular_angular.js:1580(anonymous
function) @ angular_angular.js:28829jQuery.Callbacks.fire @
jquery.js:3143jQuery.Callbacks.self.fireWith @
jquery.js:3255jQuery.extend.ready @ jquery.js:3467completed @
jquery.js:3498